{{- range $srvName, $srvValue := .Values.applications }}
{{- if and $srvValue.secrets (kindIs "map" $srvValue.secrets) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resourceName" $ }}-{{ $srvName }}-secret
type: kubernetes.io/opaque
stringData:
   {{- range $secretName, $secretValue := $srvValue.secrets }}
    {{ $secretName }}: {{ $secretValue | quote }}
   {{- end }}
{{- end }}
{{- end }}
