urls: []

gateway:
  enabled: true
  selector:
    "istio.io/rev": stable
    istio: internal-ingress
  tlsCertificate: 
    enabled: true
    issuerName: "teparak-dev-letsencrypt-acme-dns-ci"
    privateKey:
      size: 4096
