{{- if .Values.cicd.enabled -}}
{{- $resourceName := printf "%s-%s" .Values.application.name .Values.application.environment | trimSuffix "-" -}}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ $resourceName }}-cicd
  namespace: {{ .Release.Namespace }}
  labels:
    organization: {{ $.Values.global.organization }}
    application.name: {{ $.Values.application.name | quote }}
    application.env: {{ $.Values.application.environment | quote }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ $resourceName }}-cicd-sa-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ $resourceName }}-cicd
  labels:
    organization: {{ $.Values.global.organization }}
    application.name: {{ $.Values.application.name | quote }}
    application.env: {{ $.Values.application.environment | quote }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $resourceName }}-role-binding
  namespace: {{ .Release.Namespace }}
  labels:
    organization: {{ $.Values.global.organization }}
    application.name: {{ $.Values.application.name | quote }}
    application.env: {{ $.Values.application.environment | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ $resourceName }}-cicd
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $resourceName }}-cicd-role
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $resourceName }}-cicd-role
  namespace: {{ .Release.Namespace }}
  labels:
    organization: {{ $.Values.global.organization }}
    application.name: {{ $.Values.application.name | quote }}
    application.env: {{ $.Values.application.environment | quote }}
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
      - extensions
      - apps
      - networking.istio.io
    resources:
      - '*'
  - verbs:
      - '*'
    apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
{{- end }}