{{- $workOrderName := printf "patch-image-registry-sync" -}}
{{- $serviceAccountName := printf "%s-sa-%s" $workOrderName .Release.Name -}}
{{- $shouldRun := ""}}
{{- if .Values.cicd.enabled }}
{{- $shouldRun = "enabled" }}
{{- else}}
{{- $shouldRun = "disabled" }}
{{- end }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ $serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    organization: {{ $.Values.global.organization }}
    application.name: {{ $.Values.application.name | quote }}
    application.env: {{ $.Values.application.environment | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $workOrderName }}-role-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resourceNames:
    - {{ .Release.Namespace | quote }}
  resources:
    - "namespaces"
  verbs:
    - "get"
    - "patch"
- apiGroups: [""]
  resourceNames:
    - {{ .Release.Namespace | quote }}
  resources:
    - "serviceaccounts"
  verbs:
    - "get"
    - "list"
    - "patch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $workOrderName }}-role-binding-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $workOrderName }}-role-{{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ $serviceAccountName }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $workOrderName }}-job-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  parallelism: 1
  backoffLimit: 0
  ttlSecondsAfterFinished: 3600
  activeDeadlineSeconds: 120
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: {{ $serviceAccountName }}
      restartPolicy: Never
      containers:
      - name: label-ns-{{ .Release.Name }}
        image: panteparak/k8s-patcher:dev
        imagePullPolicy: Always
        command:
        - "/bin/bash"
        - "-c"
        - "patch-service-account-image-pull-secret-{{ $shouldRun }}.sh"
---