# name: release-chart
# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# permissions:
#   contents: write
#   pages: write
#   id-token: write

# concurrency:
#   group: "pages"
#   cancel-in-progress: false

# jobs:
#   release-chart:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Publish Helm chart
#         uses: stefanprodan/helm-gh-pages@v1.7.0
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           branch: gh-pages
#           target_dir: charts
#           index_dir: /


name: Release Helm Charts

concurrency:
  group: "pages"
  cancel-in-progress: false

on:
  workflow_dispatch:
  push:
    branches:
      - main
    # pull_request:
    #   branches: [ "main" ]
    paths:
      - "charts/**"

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
